package com.miguelduval.mpcmk2groovebox;
final class MpcStudioMk2SemanticActions {
 static final int NAVIGATE_MAIN=1,NAVIGATE_TRACK_VIEW=2,NAVIGATE_GRID=3,NAVIGATE_WAVEFORM=4,NAVIGATE_SAMPLE_EDIT=5,
 NAVIGATE_PAD_MIXER=6,NAVIGATE_TRACK_MIXER=7,NAVIGATE_SEQUENCE_LAUNCHER=8,NAVIGATE_BROWSE=9,NAVIGATE_SAMPLER=10,NAVIGATE_STEP=11,
 BROWSER_UP=12,TRACK_SELECTION_CONTEXT=13,SEQUENCE_SELECTION_CONTEXT=14,PROGRAM_SELECTION_CONTEXT=15,TRACK_TYPE_SELECTION_CONTEXT=16,
 DATA_DIAL_DELTA=17,DATA_DIAL_PRESS=18,ADJUST_VALUE_DELTA=19,PAD_BANK_CHANGED=20,NOTE_REPEAT_STATE=21,FULL_LEVEL_STATE=22,HALF_LEVEL_STATE=23,
 PAD_MUTE_MODE_STATE=24,TRACK_MUTE_MODE_STATE=25,TRANSPORT_RECORD=26,TRANSPORT_OVERDUB=27,TRANSPORT_STOP=28,TRANSPORT_PLAY=29,
 TRANSPORT_PLAY_START=30,TRANSPORT_RESET=31,STEP_LEFT=32,STEP_RIGHT=33,BAR_LEFT=34,BAR_RIGHT=35,TAP_TEMPO=36,TOUCH_STRIP_VALUE=37,
 LOCATE_STATE=38,LOCATE_PAD=39,SAMPLE_SELECT_CONTEXT=40,SAMPLE_START_CONTEXT=41,SAMPLE_END_CONTEXT=42,TUNE_CONTEXT=43,QUANTIZE=44,
 TIMING_CORRECT_STATE=45,ZOOM_CONTEXT=46,COPY_CONTEXT=47,UNDO=48,AUTOMATION_CONTEXT=49,PAD_MUTE_TARGET=50,TRACK_MUTE_TARGET=51,SIXTEEN_LEVEL_STATE=53,RESERVED=52;
 private MpcStudioMk2SemanticActions() {}
}